In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
a = [[1,2,3],[4,5,6]]
A= np.array(a)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
A.shape

(2, 3)

In [4]:
A.ndim

2

In [5]:
A.size

6

In [14]:
A[1][1]

5

In [15]:
A[1,1]

5

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = -np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.dot(a,b)
c

array([[ -30,  -36,  -42],
       [ -66,  -81,  -96],
       [-102, -126, -150]])

In [25]:
500/(np.pi*1e6*(2.84e-3)**2)

19.73256088721178

In [28]:
q = np.array([[-1,2,1],[2,3,0]])
w = np.array([[0,-4],[2,-1],[1,-2]])
e = np.dot(q,w)
e

array([[  5,   0],
       [  6, -11]])

In [40]:
e.shape

(2, 2)

In [31]:
e.ndim

2

In [32]:
z = np.array([[0,1,3],[-2,1,3],[-2,-1,4]])
x = np.array([[1,1,-2],[-3,1,2],[0,1,1]])
z*x

array([[ 0,  1, -6],
       [ 6,  1,  6],
       [ 0, -1,  4]])

In [33]:
np.dot(z,x)

array([[-3,  4,  5],
       [-5,  2,  9],
       [ 1,  1,  6]])

In [35]:
z.T

array([[ 0, -2, -2],
       [ 1,  1, -1],
       [ 3,  3,  4]])

In [41]:
a=np.array([-1,1])
b=np.array([1,1])
c = np.dot(a,b)

In [42]:
c.shape

()